### ISSUE TITLE
Full name or first and last name? What one should we use?

### ISSUE THREAD

**Issue by mittalyashu** [logchimp/logchimp#101]
For storing user's name. What kind of data will be most suitable.
Storing `fullname` in a single column or splitting into `firstname` and `lastname`.

Please share your thoughts.

**Comment by tiredofit** [comment]
`username` is commonly accepted along with seperate fields for Given and Surname.

**Comment by mittalyashu** [comment]
Closed by https://github.com/logchimp/logchimp/pull/235
