### ISSUE TITLE
NOTICE: LICENSE change in-near future

### ISSUE THREAD

**Issue by mittalyashu** [logchimp/logchimp#106]
This is an issue to inform you that in-near future, we're changing the LICENSE of all repositories in [LogChimp](https://github.com/logchimp) organisation.

I am still looking for a LICENSE, most probably will be one of these 3:
* Apache
* MPL
* GNU

**Why a sudden change?**

We love open source and from day-one planned to keep the source code open source, while bad actors are lurking out there, it's not 100% possible to stop the misuse. We believe by using an appropriate LICENSE, the cause can be minimised.

**How does it affect LogChimp as an open-source project?**

It doesn't affect LogChimp in any way, as we continue to adopt the power of open source and build a better version of LogChimp.

You can subscribe to this issue for further updates for the same.

Please share your thoughts and suggestions below.

**Comment by mrdotkg** [comment]
Hey @mittalyashu, What king of misuse people do? I would like to know about that too. 

What exactly would you like to restrict through next license?

**Comment by mittalyashu** [comment]
**UPDATE** _(March 17, 2021)_

To all the users who have subscribed to this issue and existing contributors.

Commits starting from fb7190a4aa8e1da9ec977dd1d4c8dfab9d536be4 will fall under [this LICENSE](#461).
