### ISSUE TITLE
Resolve "no-mutate-props" (eslint error) for Post.vue component

### ISSUE THREAD

**Issue by mittalyashu** [logchimp/logchimp#135]
The error is shown by vue eslint for "no-mutation-props", as we're modifying the props `post` when there an event call from `updateVoters`.

```js
updateVoters(voters) {
  // eslint-disable-next-line vue/no-mutating-props
  this.post.voters = voters;
}
```
[source](https://github.com/logchimp/logchimp/blob/master/frontend/src/components/post/Post.vue#L72-L75)

**Comment by HunterJS-bit** [comment]
@mittalyashu Hi could I work on this issue ?

**Comment by mittalyashu** [comment]
Hello @HunterJS-bit,

Sure, you can work on this issue.

**Comment by HunterJS-bit** [comment]
@mittalyashu created pull request #162

**Comment by HunterJS-bit** [comment]
@mittalyashu updated and created new pull request #163

**Comment by HunterJS-bit** [comment]
@mittalyashu   can you please let me know if this PR is that you wanted.

**Comment by mittalyashu** [comment]
@HunterJS-bit Apologies for delay and thank you for submitting the PR.

I will review it by today.

**Comment by mittalyashu** [comment]
This issue is already resolved.

_Don't remember the PR, though 😅_
