### ISSUE TITLE
Fix JWT Sign token

### ISSUE THREAD

**Issue by Mohammedalasaad** [logchimp/logchimp#166]
Hi,
There is an issue when user login, its need to be like this. I am using mysql btw!.

/logchimp/server/utils/token.js
```
// modules
const jwt = require("jsonwebtoken");

exports.createToken = (data, secretKey, payload) => {
	const token = jwt.sign({ data: data }, secretKey, payload);
	return token;
};
```

Another issue is with Create date and update date., I think It need to be like this
logchimp/server/services/auth/createUser.js
```
			.insert({
				userId,
				username,
				password: hashedPassword,
				avatar,
				...user,
				createdAt: new Date(),
				updatedAt: new Date()
			})
			.into("users")

```

**Comment by mittalyashu** [comment]
Hello @Mohammedalasaad 

* Can you share the steps to reproduce the error?
* What kind of error did you got in the browser console?
* Can you share the logs from `content/logs` directory _(if possible)_

**Comment by MohammedAlasaad** [comment]
Hi @mittalyashu 
The steps i am just trying to login ( this is for the first issue JWT ) 

Error shows on frontend terminal
Proxy error: Could not proxy request /api/v1/auth/login from localhost:8080 to http://localhost:3000.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNRESET).

error from logchimp-all.log:
2020-10-17 14:14:17 +02:00 ERROR: Error: Expected "payload" to be a plain object.

error from logchimp-error.log
2020-10-17 14:14:17 +02:00 ERROR: Error: Expected "payload" to be a plain object.

Browser no errors shoes, Its just keep loading to login.. but it fail at the end.


Seond issue regarding createUser, (the date) If we use .toJSON() I got this when I try to signup 

{message: "User not found", code: "USER_NOT_FOUND"}
code: "USER_NOT_FOUND"
message: "User not found"

Error from log file:
2020-10-17 14:22:00 +02:00 WARN: [object Object]
2020-10-17 14:22:00 +02:00 ERROR: Error: insert into `users` (`avatar`, `createdAt`, `emailAddress`, `firstname`, `isOwner`, `lastname`, `password`, `updatedAt`, `userId`, `username`) values ('https://www.gravatar.com/avatar/b642b4217b34b1e8d3bd915fc65c4452', '2020-10-17T12:22:00.133Z', 'test@test.com', '', false, '', '$2a$10$VlJdvLcLfbFadLIIHuZCOuXueb1xsMlKU7YeVNzBGe0Fbkf99U.Rm', '2020-10-17T12:22:00.133Z', '27763d61-e410-40d8-8c44-1ea79a7222a6', 'test') - ER_TRUNCATED_WRONG_VALUE: Incorrect datetime value: '2020-10-17T12:22:00.133Z' for column `logchimp`.`users`.`createdAt` at row 1

**Comment by mittalyashu** [comment]
@Mohammedalasaad

> Proxy error: Could not proxy request /api/v1/auth/login from localhost:8080 to http://localhost:3000.

This error means you're not connected to the backend server.

Are you running the LogChimp in production or development?

> error from logchimp-all.log:
> 2020-10-17 14:14:17 +02:00 ERROR: Error: Expected "payload" to be a plain object.
>
> error from logchimp-error.log
> 2020-10-17 14:14:17 +02:00 ERROR: Error: Expected "payload" to be a plain object.

Did you got the payload error while trying to login?

> {message: "User not found", code: "USER_NOT_FOUND"}
> code: "USER_NOT_FOUND"
> message: "User not found"

The above error means that you're using the credentials of the user which doesn't exists in the database.

> (the date) If we use .toJSON() I got this when I try to signup

Regarding the issue with date, we're not sure why it is storing the date in different format, we'll investigate into it. Thank you for sharing the bug report.

---

Can you run this code `new Date().toJSON()` in your browser console and share the return value?

**Comment by MohammedAlasaad** [comment]
> Proxy error: Could not proxy request /api/v1/auth/login from localhost:8080 to http://localhost:3000.
> This error means you're not connected to the backend server.
> Are you running the LogChimp in production or development?
> 

How is that possible not connected to backend server and It running and I can access for ex login, signup. but when trying to login so it fail?
I am just running locally and its development.

> Did you got the payload error while trying to login?


Yes when I try to login it fail if we have, and the user exist on the database.
 	const token = jwt.sign(data, secretKey, payload);
but it works if I change it to 
	const token = jwt.sign({data: data}, secretKey, payload); 
or like this 	**const token = jwt.sign({ data }, secretKey, payload);**
And I think thats how it should be.. example from JWT

> var token = jwt.sign({
>     userId: '110095',
>     name: 'John Doe',
>     roles: ['writer', 'moderator']
> }, SECRET, { expiresIn: "7d" }); // default: HS256 encryption
> 

btw if I write wrong password it seems to work 
{message: "Incorect password", code: "INCORRECT_PASSWORD"}
code: "INCORRECT_PASSWORD"
message: "Incorect password"

> {message: "User not found", code: "USER_NOT_FOUND"}
> code: "USER_NOT_FOUND"
> message: "User not found"

I get this when I try to create new user! not when I try to login!

And here when I do console for toJSON console.log( new Date().toJSON() ) 
2020-10-18T09:25:06.908Z

**Comment by mittalyashu** [comment]
This issue should not happen in [v0.5.0](https://github.com/logchimp/logchimp/releases/tag/v0.5.0).
