### ISSUE TITLE
Error when post request like create board or save settings

### ISSUE THREAD

**Issue by Mohammedalasaad** [logchimp/logchimp#169]
Is there anyway to debug and see what is the issue here. I am trying to create new Board but seems not working! and not any post request. like save settings or so..

Proxy error: Could not proxy request /api/v1/boards from localhost:8080 to http://localhost:3000.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNRESET).

2020-10-16 19:44:01 +02:00 ERROR: Error: Undefined binding(s) detected when compiling SELECT. Undefined column(s): [userId] query: select * from `users` where `userId` = ? limit ?

**Comment by mittalyashu** [comment]
Hello @Mohammedalasaad, can you share the steps to reproduce the error?

Where were you trying to create a board? From setup page or dashboard.

MySQL is not officially supported yet, did you try with PostgreSQL?

**Comment by MohammedAlasaad** [comment]
I would like to use mysql, easier locally :) I just installed mysql package and changed the client in config to mysql instead of pg as knex will work.
I am trying to create board from here http://localhost:8080/dashboard/create-board

**Comment by mittalyashu** [comment]
_Closing this issue due to stale activity._
