### ISSUE TITLE
Different roles for users

### ISSUE THREAD

**Issue by tiredofit** [logchimp/logchimp#173]
It would be ideal to have multiple roles for users.

a) Admin
b) Regular user (with ability to define which boards they have access to)
c) Product Owner (with ability to define which boards they have access to respond/manage to)
d) Anonymous.

**Comment by mittalyashu** [comment]
@tiredofit 

> Regular user (with ability to define which boards they have access to)

What do you mean by "ability to define which boards they have access to"? Do you want only selected users to have access to a specific board?

> Product Owner (with ability to define which boards they have access to respond/manage to)

What kind of permissions do you want the product owner to have?

> Anonymous

What do you mean by "Anonymous" users?

**Comment by tiredofit** [comment]
In terms of regular user:
- Maybe by default they have access to all boards, but it would be good to limit their access to perhaps no boards, or only a specific set of boards. This opens the idea up of public vs private boards as well.

- Product Owner - Ability to edit suggestions, moderate/edit/delete comments, change "status" of suggestion (Under consideration/in progress)

- Anonymous meaning - that users could see the boards without logging in, however not make any updates/suggestions to the boards.

**Comment by mittalyashu** [comment]
> This opens the idea up of public vs private boards as well.

Can you share your use-cases for private boards?

**Comment by tiredofit** [comment]
Take for example I have one installation of Logchimp, yet I have my users defined in various Groups or roles (say being passed by an OIDC authorization flow, or in the application itself). I would like to limit certain users from seeing specific groups, certain users from being able to administer a board, certain users to be able to administer the entire instance.

Alternatively I could spin up multiple copies of Logchimp, however that creates significant overhead for maintaining seperate systems.

**Comment by mittalyashu** [comment]
@tiredofit We've just re-written our roles and permission logic and added a bunch new feature related to it. This update will be release in v0.6.0.

To avoid over head complexity at early stage, there're not plans to add permission at boards level in near-future.

You can give these new feature a try by spinning up a development environment of LogChimp locally on your machine and don't forget to share your feedback 🙂
