### ISSUE TITLE
Get posts, board and votes in single SQL query

### ISSUE THREAD

**Issue by mittalyashu** [logchimp/logchimp#223]
I have written this SQL query to post, board and votes data (PostgreSQL 12.4)

You can check the [working example](https://www.db-fiddle.com/f/rCAkAopBxQa42NUufnE6mu/1) to see db query and results.

This is the query where the issue is:

```sql
json_agg(
    (
      SELECT
        vp
      FROM
        (
          SELECT
            v."voteId",
            v."userId",
            v."postId"
        ) AS vp
    )
  ) AS votes
```

![CleanShot_2020-12-23_at_16 54 392x](https://user-images.githubusercontent.com/29014463/102994940-12c72380-4546-11eb-9f20-68511ebf4e44.png)

This query in `votes` column returns an array of objects _(see above image)_. But I need to limit the number of items by 10.

**NOTE:** I have already tried using `LIMIT` and it didn't work.

### Full SQL query

```sql
EXPLAIN ANALYSE
SELECT
  json_build_object(
    'votes_count',
    (
      SELECT
        count(*)
      FROM
        votes
      WHERE
        votes."postId" = p."postId"
    ),
    'viewer_vote',
    (
      'ee98cfca-060a-4161-a59b-18ad51406a41' = ANY (ARRAY_AGG(v."userId") :: uuid [])
    )
  ),
  json_agg(
    (
      SELECT
        vp
      FROM
        (
          SELECT
            v."voteId",
            v."userId",
            v."postId"
        ) AS vp
    )
  ) AS votes,
  p."postId",
  p."title",
  p."slug",
  p."boardId",
  p."contentMarkdown",
  json_agg(
    (
      SELECT
        bp
      FROM
        (
          SELECT
            b."boardId",
            b."name",
            b.url,
            b.color
        ) AS bp
    )
  ) AS board
FROM
  posts AS p
  INNER JOIN boards AS b ON p."boardId" = b."boardId"
  INNER JOIN votes AS v ON p."postId" = v."postId"
GROUP BY
  p."postId";
```

If you have questions regarding the above SQL query, drop a message in the comments below.

**Comment by xzilla** [comment]
I think you really need to provide more information to get reasonable help; you say you tried limit but it didn't work, but it is unclear where/how you tried it, and if you got an error or different results from what you expected. Maybe you could use an sqlfiddle to put together a complete example that others could then work from? 

FWIW, I put together a quick example from the pagila sample database which I think shows an example of what you are trying to do... hopefully it helps?
```
pagila=# select json_agg(x) from (select x from (select first_name,last_name from actor limit 3) x ) xx ;
                      json_agg
----------------------------------------------------
 [{"first_name":"PENELOPE","last_name":"GUINESS"}, +
  {"first_name":"NICK","last_name":"WAHLBERG"},    +
  {"first_name":"ED","last_name":"CHASE"}]
(1 row)
```

**Comment by mittalyashu** [comment]
@xzilla Thank you for taking your time and looking into this issue.

Here's the link to working example: https://www.db-fiddle.com/f/rCAkAopBxQa42NUufnE6mu/1
