### ISSUE TITLE
Setup Account Process doesn't work

### ISSUE THREAD

**Issue by devhawkio** [logchimp/logchimp#247]
**Describe the bug**
Cannot complete the setup process as I receive an INVALID JWT error.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start with a clean database
2. Start the program.
3. Setup the first account
4. When trying to create a board, an INVALID JWT error is received

**Expected behaviour**
The board should be created.

**Comment by mittalyashu** [comment]
Hello @devhawkio,

Is the issue related to setting up the site or creating a new board?

**Comment by devhawkio** [comment]
When setting up the site it prompts the user to create a new board.

Thank you,
Bobby Lansing
CEO, DEVHAWK
________________________________

**Comment by mittalyashu** [comment]
Thanks for the information, I will look into it.

**Comment by mittalyashu** [comment]
@devhawkio This fix has been released in https://github.com/logchimp/logchimp/releases/tag/v0.5.0
