### ISSUE TITLE
Account Creation Email doesn't send

### ISSUE THREAD

**Issue by devhawkio** [logchimp/logchimp#248]
**Describe the bug**
verifyEmail function is missing a variable:
`const verifyEmail = async (url, email) => {
`

Replace with:
`const verifyEmail = async (domain1, url, email) => {
`
Domain1 is not used, but the order of the variables as sent must be maintained so that the email goes to the correct recipient

**Comment by mittalyashu** [comment]
Let me look into it and get back to you.

**Comment by mittalyashu** [comment]
Closed by https://github.com/logchimp/logchimp/commit/a4032a51939f7f873051f002a158fa7cf226f330

**Comment by mittalyashu** [comment]
@devhawkio This issue have been fixed.

Let me know if you're still facing similar issue.
