### ISSUE TITLE
Foreign key in emailVerification table breaks the user account creation process

### ISSUE THREAD

**Issue by devhawkio** [logchimp/logchimp#250]
Log file says:
2020-12-14 15:27:58 -08:00 ERROR: insert into "emailVerification" ("email", "token") values ($1, $2) returning * - insert or update on table "emailVerification" violates foreign key constraint "emailverification_email_foreign"

Remove the foreign key requirement and this problem is fixed.
Perhaps the user is not in the database yet when the emailverification value is added?

**Comment by mittalyashu** [comment]
Most probably it’s the bug from recent commits I have made for [v0.5.0](https://github.com/logchimp/logchimp/milestone/8), that might have caused the issue.

Will look into it, thanks.

**Comment by mittalyashu** [comment]
@devhawkio Can you share additional information about this bug? Like hare the steps to reproduce the error.

**Comment by mittalyashu** [comment]
@devhawkio we've just release [v0.5.0](https://github.com/logchimp/logchimp/releases/tag/v0.5.0) with features, improvements and bug fixes.

_Closing this issue for now_. Feel free to re-open in case you're facing this issue again.
