### ISSUE TITLE
Email setup required in documentation and automation

### ISSUE THREAD

**Issue by devhawkio** [logchimp/logchimp#251]
There is no clear documentation or automation around email server and account config.
Here is an example:
`  "mail": {
    "host": "EMAIL_HOST",
    "port": PORT_NO,
    "user": "EXAMPLE_USER",
    "password": "EXAMPLE_PASS"
  }`

This must be added to the logchimp.config.json in order to send verification emails.

**Comment by mittalyashu** [comment]
What kind of automation are you looking for?

Using [LogChimp CLI](https://github.com/logchimp/logchimp-cli) you can easily setup a site, though, a newer version haven’t released yet as it still work in progress
