### ISSUE TITLE
GET vs POST

### ISSUE THREAD

**Issue by devhawkio** [logchimp/logchimp#253]
Check each occurrence of GET and POST API calls. A few POSTs are in the place where it should be GET.
Example: 
getBoardsbyUrl
getPosts

**Comment by mittalyashu** [comment]
I am already aware of that bug.

Will soon commit a fix for that.

**Comment by mittalyashu** [comment]
Closed by https://github.com/logchimp/logchimp/commit/7d503cac9323b1d2260dd9bd1614481f392edec9

**Comment by devhawkio** [comment]
Typically a development team does not close issues unless there is already an issue for it or a commit is made fixing the issue. Just a heads up.
