### ISSUE TITLE
Case insensitive emails while creating an account

### ISSUE THREAD

**Issue by mittalyashu** [logchimp/logchimp#532]
**Describe the bug**
A user can create multiple accounts by having different casing in the email address.

**Expected behaviour**
It should check the email by lower casing it.

**Comment by tnmyk** [comment]
Can you assign me?

**Comment by abel-mak** [comment]
Hi, i want to help.

**Comment by mittalyashu** [comment]
Hello @abel-mak,

You're most welcome to work on this issue, let me know if you have any questions.

**Comment by abel-mak** [comment]
thanks, the change should be in `server/services/auth/createUser.js`?

**Comment by mittalyashu** [comment]
> thanks, the change should be in `server/services/auth/createUser.js`?

yes

**Comment by abel-mak** [comment]
can you check change befor PR:
https://github.com/abel-mak/logchimp/commit/a0ea528112663528509c74e00556d1d702c515e7

**Comment by mittalyashu** [comment]
You need to lowercase the value in database query as well.

**Comment by paltannistha** [comment]
Hey I would like to work on this issue. I'm new to open source. Please guide me how to get started?

**Comment by mittalyashu** [comment]
Hello @paltannistha, welcome to LogChimp.

To get started with contribution, you can follow the following steps:
1. Fork this repository
2. Clone the repository locally on your machine and make the required changes.

Please don't hesitate to ask any questions 🙂

**Comment by paltannistha** [comment]
@mittalyashu  okay thank you. But can u please guide me when I should create the PR? As this year I want to take part in Hacktoberfest, so should create the pull request once the event gets started?

**Comment by paltannistha** [comment]
@mittalyashu okay thank you. But can you please guide me when I should create the PR? As this year I want to take part in Hacktoberfest, so should I create the pull request once the event gets started?

**Comment by mittalyashu** [comment]
> @mittalyashu okay thank you. But can you please guide me when I should create the PR? As this year I want to take part in Hacktoberfest, so should I create the pull request once the event gets started?

Yes, @paltannistha. You need to link your GitHub account with Hacktoberfest.
