### ISSUE TITLE
Account verification via email

### ISSUE THREAD

**Issue by mittalyashu** [logchimp/logchimp#7]
Send email to the member's account for email verification.

### Links

* Source code: https://github.com/logchimp/logchimp/blob/master/server/controllers/auth/signup.js#L81
* Documentation: https://nodemailer.com/about/

**Comment by mittalyashu** [comment]
@CodingCreate101 I am planning to use mailgun for sending emails.

What do you think?

**Comment by tejas-hosamani** [comment]
Does that mean, those who self-host this app, need mailgun account? That's seems like another dependency and it's not free either. There is a package called `nodemailer`, with which we can emails. Maybe consider that?
