### ISSUE TITLE
Error in Gitpod

### ISSUE THREAD

**Issue by soundstep** [logchimp/logchimp#709]
**Describe the bug**

In Gitpod:

<img width="746" alt="Screenshot 2022-08-04 at 13 10 29" src="https://user-images.githubusercontent.com/133293/182843822-60a29c4d-2de8-410a-b3fb-a5613c9c1e87.png">

**To Reproduce**
Steps to reproduce the behaviour:
1. Click on open in Gitpod there: https://logchimp.codecarrot.net/docs/install/gitpod

**Expected behaviour**
Logchimp running I guess

**Comment by mittalyashu** [comment]
Hi @soundstep,

This issue has been fixed by the following commits:
* https://github.com/logchimp/logchimp/commit/06fed9b4002160c4740f90f976f315fd979f8898
* https://github.com/logchimp/logchimp/commit/3f34c7f3c9ab938107662971dee3bb1464e4bc33

Let me know if you're still facing this issue. 🙂
