### ISSUE TITLE
Railway Deployment Account Setup Broken

### ISSUE THREAD

**Issue by andrewdmaclean** [logchimp/logchimp#710]
**Describe the bug**
When attempting to host the app following the Deploy from Railway button, you are unable to create an account due to a 404 error.

**To Reproduce**
1. Follow instruction on https://logchimp.codecarrot.net/docs/install/railway
2. Attempt to create an account or login
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/26526271/183228787-0e5d67a4-b60d-4603-a03f-4f9d8ee14201.png)

**Additional context**
The issue is that the baseURL is duplicated in the API calls.

**Comment by mittalyashu** [comment]
Hey @andrewdmaclean,

Thank you for bringing that problem to my notice. I've [fixed the Railway one-click deploy template](https://github.com/logchimp/website/commit/fd26fb96ed8cfa85cbd7dbbaa9f2582a5afa6fa5). Can you please try again.

I'll close this issue for now, please don't hesitate to reopen this issue incase you faced any similar problem. 🙂
