### ISSUE TITLE
"Cannot GET /" on Railway

### ISSUE THREAD

**Issue by egger** [logchimp/logchimp#762]
I tried to install LogChimp on Railway. I followed the docs and LogChimp was successfully installed but after visiting the website I got this message "Cannot GET /".

**Reproduce**
1. Click "Deploy on Railway"
2. Create your repository and fill in the LogChimp Secret Key and SMPT mail authentication details. 
3. Scroll down and click "Deploy"
4. It successfully installs but after going to the website it will show the message "Cannot GET /".

**Screenshots**

![image](https://user-images.githubusercontent.com/26516815/197821554-c2282436-1db0-45c1-bcf0-27eb4c1c0511.png)

**Version used**
 - LogChimp [Stable version]

**Comment by mittalyashu** [comment]
Hello @egger,

Thank you for reporting this issue. I've making some changes to `v0.7.x` behind the scenes causing the break the Railway deployment.

I've [updated the docs](https://logchimp.codecarrot.net/docs/install/railway) for the same, try again and let me know.

I'll mark this issue as closed for now, please don't hesitate to re-open the issue if you're same problem again 🙂

**Comment by mittalyashu** [comment]
Closed by https://github.com/logchimp/website/commit/2fcfcac6e4f4101fb11f82f84340ffd5450c118b
