### ISSUE TITLE
Railway: Deployment Failed during build process

### ISSUE THREAD

**Issue by jtechbit** [logchimp/logchimp#847]
**Describe the bug**
Railway 'one click' deploy is failing - Error: No start command could be found.

**To Reproduce**
Steps to reproduce the behaviour:
1. Navigate to https://logchimp.codecarrot.net/docs/install
2. Click on 'Render' - one click deploy
3. Generate secret key and paste into env variable
4. Enter email variables
5. Deploy

**Expected behaviour**
Build succeeds and backend is deployed

**Screenshots**
![2023-08-14 at 16 53 42](https://github.com/logchimp/logchimp/assets/131580883/dc42572d-cd37-4003-b6c2-e79007804bd3)

**Comment by mittalyashu** [comment]
It seems this issue got originated due to change in Railway platform.

It has been fixed by https://github.com/logchimp/logchimp/commit/c90d09fe7ac843a0d589f0ee3e86aa95e642112d
