### ISSUE TITLE
Remove 'description' from alerts vuex store

### ISSUE THREAD

**Issue by mittalyashu** [logchimp/logchimp#89]
Reference: https://github.com/logchimp/logchimp/pull/83/commits/b329df296fc1d222c1eed19bb9d977615bb391f6

**Comment by vandana1499** [comment]
@mittalyashu I would like to work on this .

**Comment by mittalyashu** [comment]
Hello @vandana1499,

Thank you for showing your interest in contributing to [LogChimp](https://github.com/logchimp/logchimp) project.
